// app/head.js
export default function Head() {
    return (
      <>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
      </>
    );
  }
  